#!/usr/bin/env bash

### SETTINGS ###

# this is what TAB will insert.
# default value is "  ". possible values are any string.
tabchar="  "

# auto tab with bim_insert, bim_backinsert, or when ENTER is pressed in insert mode.
# default value is "0". possible values are 0 or 1.
autotab="0"

### MACROS ###

# create a shell function with a name and edit contents.
# not horribly useful, but a good showcase of bim's extensibility.
mc_shellfunc() {
	# name defaults to func if not given
	[ "$1" ] && name="$1" || name="func"
	# create 3 lines
	bim_blank 3
	# create function skeleton
	buffer[line+1]="${name}() {"
	buffer[line+2]="${tabchar:="  "}"
	buffer[line+3]="}"
	# edit contents
	bim_down 2; bim_edit
}

# draws a smile :)
mc_smile() {
    bim_blank 4
	buffer[line+1]="  #  #  "
	buffer[line+2]="        "
	buffer[line+3]="#      #"
	buffer[line+4]=" ###### "
}

# 'keybinds' is a special function that is called every time a key is pressed.
# on start, bim checks to see if it is defined.
# these keybinds are defaults, with additional bindings for macros in this RC file.
keybinds() {
    case "${key}" in
    
        # motions
        k) bim_up 1;;
        j) bim_down 1;;
        K) bim_up $((LINES - 4));;
        J) bim_down $((LINES - 4));;
		g) bim_bof;;
		G) bim_eof;;
        t) cursor show
           bim_goto "$(misc_prompt "goto: ")"
           cursor hide
           ;;

        # editing
        a) bim_edit;;
        I) bim_prepend;;
        d) bim_delete;;
        c) bim_clear;;
        o) bim_insert;;
        O) bim_backinsert;;
        n) bim_blank 1; bim_down 1;;
        N) bim_backblank 1;;
        y) bim_yank;;
        p) bim_paste; bim_down 1;;
    
        # misc
        :) bim_prompt;;
		z) bim_center;;

		# rc macros
		F) cursor show
		   mc_shellfunc "$(misc_prompt "function name: ")"
		   cursor hide
		   ;;
        S) mc_smile;;
    esac
}
